name: Publish Transformations to Rudder workspace

on:
  pull_request:
    branches:
      - main

jobs:
  request:
    runs-on: ubuntu-latest
    env:
      TEST_ONLY: true
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Rudder Transformation Action
        uses: rudderlabs/rudder-transformation-action@v1.1.2
        with:
          metaPath: "./code/meta.json"
          email: "abhimanyu@rudderstack.com"
          accessToken: ${{ secrets.TRANSFORMATION_API_ACCESS_TOKEN }}
          uploadTestArtifact: true
